doodle_app/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'items#index'
  resources :items do
    resources :comments
  end
  get 'search' => 'items#search'
end

doodle_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

doodle_app/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :item
end

doodle_app/app/models/item.rb
class Item < ApplicationRecord
  require 'mini_magick'
  searchkick
  paginates_per 9
  has_one_attached :image
  has_many :comments
  belongs_to :user
  has_many :steps, inverse_of: :item
  accepts_nested_attributes_for :steps, reject_if: :all_blank, allow_destroy: true

  def date_created
    self.created_at.strftime("on %d %B %Y")
  end

  def date_updated
    self.updated_at.strftime("on %d %B %Y")
  end
  
  def index_image
    self.image.variant(resize: '1200x2400').processed
  end

  def mini_test
    self.image.variant(combine_options: { gravity: "center", crop: "200x200+0+0" })
  end

  def width
    self.image.metadata[:width]
  end

  def height
    self.image.metadata[:height]
  end

  def aspect_ratio
    self.width / self.height.to_f
  end

  def square_image
    if aspect_ratio > 1
      self.image.variant(combine_options: { gravity: "center", crop: "#{height}x#{height}+0+0" })
    else
      self.image.variant(combine_options: { gravity: "center", crop: "#{width}x#{width}+0+0" })
    end
  end
end

doodle_app/app/models/step.rb
class Step < ApplicationRecord
  belongs_to :item
end

doodle_app/app/models/user.rb
class User < ApplicationRecord
  has_many :items
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

doodle_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

doodle_app/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @item = Item.find(params[:item_id])
    @comment = @item.comments.build(params[:comment].permit(:subject, :body))

    if @comment.save
      CommentsMailer.with(comment: @comment).post_comment.deliver_now
      flash[:notice] = 'Comment was successfully saved!'
      redirect_to @item
    else
      flash[:alert] = 'Comment could not be saved!'
      redirect_back fallback_location: @item
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:subject, :body)
  end
end

doodle_app/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all.page params[:page]
  end

  def show
    @item = Item.find params[:id]
  end

  def new
    @item = current_user.items.build
  end

  def create
    @item = current_user.items.build(item_params)

    if @item.save
      redirect_to @item
    else
      redirect_to items_path
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.last_edited_by = current_user

    if @item.update(item_params)
      flash[:notice] = "Updated successfully!"
      redirect_to @item
    else
      flash[:alert] = "Failed to update!"
      render 'edit'
    end
  end

  def search
    @items = Item.search params[:search]
  end

  private

  def item_params
    params.require(:item).permit(:title, :image, steps_attributes: [ :id, :content, :_destroy ])
  end


end

doodle_app/app/helpers/application_helper.rb
module ApplicationHelper
end

doodle_app/app/helpers/comments_helper.rb
module CommentsHelper
end

doodle_app/app/helpers/items_helper.rb
module ItemsHelper
end

doodle_app/app/views/comments/_comment.html.haml
%p= comment.subject
%p= comment.body

doodle_app/app/views/comments/_form.html.haml
= form_with model: [ @item, @item.comments.build ] do |f|
  %P= f.text_field :subject
  %p= f.text_area :body
  %p= f.submit

doodle_app/app/views/items/_form.html.haml
= form_with model: @item do |f|
  %P= f.text_field :title
  %p= f.file_field :image
  %h4 Steps
  #steps
    = f.fields_for :steps do |step| 
      = render 'step_fields', f: step
    .links
      = link_to_add_association 'add step', f, :steps

  %p= f.submit

doodle_app/app/views/items/_item.html.haml
.row
  - @items.each do |item|
    .col-4.mt-4
      = link_to item do
        .card.shadow
          = image_tag item.square_image, class: "card-img-top"

          .card-body
            %p.card-item= item.title

doodle_app/app/views/items/_step_fields.html.haml
.nested-fields
  .field
    = f.label :content
    = f.text_field :content

  = link_to_remove_association 'remove', f

doodle_app/app/views/items/edit.html.haml
= render 'form'

doodle_app/app/views/items/index.html.haml
.row.justify-content-center
  = paginate @items

= render 'item'

.row.justify-content-center.mt-4
  = paginate @items

.mb-5

doodle_app/app/views/items/new.html.haml
= render 'form'

doodle_app/app/views/items/search.html.haml
%h4.display-4
  searching...
  = params[:search]

= render 'item'

.mb-5

doodle_app/app/views/items/show.html.haml
%h2.display-2= @item.title

.row
  .col-9
    %p= Faker::Witcher.quote
  .col-3
    .btn-group.float-right.mb-2
      = link_to 'Back', :back, class: "btn btn-outline-secondary"
      = link_to 'Edit', edit_item_path(@item), class: "btn btn-outline-secondary"

.row
  .col-6
    .card
      = image_tag @item.image, class: "card-img"

    %p
      = "created by #{@item.user.username}"
      %em= @item.date_created

    - if !@item.last_edited_by.blank?
      %p
        = "last edit by #{User.find(@item.last_edited_by).username}" 
        %em= @item.date_updated


  .col-6
    .card
      .card-body
        - if @item.comments.blank?
          %p be the first to write a comment
        - else
          %p
            %em= pluralize(@item.comments.count, 'comment')
          = render @item.comments 


    .card.mt-4
      .card-body
        = render 'comments/form'

- if !@item.steps.blank?

  %h4.display-4 Steps

  - @item.steps.each do |step| 
    %p= step.content

doodle_app/app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Doodle App
    = csrf_meta_tag
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body.bg-light

    %nav.navbar.navbar-dark.bg-dark.mb-4

      .container
        .ul.nav

          = link_to 'Home', items_path, class: "navbar-brand"
          - if user_signed_in?

            %li.nav-item
              = link_to current_user.username, edit_user_registration_path, class: "nav-link"
            %li.nav-item
              = link_to 'Log Out', destroy_user_session_path, method: :delete, class: "nav-link"

          - else

            %li.nav-item
              = link_to 'Sign In', new_user_session_path, class: "nav-link"
            %li.nav-item
              = link_to 'Sign Up', new_user_registration_path, class: "nav-link"

        = form_tag search_path, method: :get, class: "form-inline" do
          = search_field_tag 'search', nil, placeholder: "monster name...", class: "form-control"
          = submit_tag "Search", class: "btn btn-secondary ml-1"

    .container.mt-2
      - flash.each do |name, msg|
        - case name
          - when 'notice'
            = content_tag :div, msg, class: "alert alert-primary"
          - when 'alert'
            = content_tag :div, msg, class: "alert alert-danger"
          - else
            %p flash message name/class not recognized

      = yield